set nocompatible
set t_Co=256
set background=light

"Vundle Experiment automatic
" Setting up Vundle -> The VIM Pluging handler
	let iCanHazVundle=1
	let vundle_readme=expand('~/.vim/bundle/vundle/README.md')
	if !filereadable(vundle_readme)
		echo "Installing Vundle..."
		echo ""
		silent !mkdir -p ~/.vim/bundle
		silent !git clone https://github.com/gmarik/vundle ~/.vim/bundle/vundle
		let iCanHazVundle=0
	endif
	set rtp+=~/.vim/bundle/vundle/
	call vundle#rc()
	Bundle 'gmarik/vundle'
	"My bundles here
	Bundle 'altercation/vim-colors-solarized'
	Bundle 'L9'
	Bundle 'FuzzyFinder'
	Bundle 'tpope/vim-fugitive'
	Bundle 'Lokaltog/vim-easymotion'
	Bundle	'scrooloose/nerdtree'
	if iCanHazVundle == 0
		echo "Vundle is installed, Installing Vundle, Please ignore keymap error messages"
			echo ""
			:BundleInstall
		endif
"Setting up Vundle -> The vim plugin bundler end

filetype on
filetype indent on
filetype plugin on

set laststatus=2
"set statusline=\ %f%m%r%h%w\ %=%({%{&ff}\|%{(&fenc==\"\"?&enc:&fenc).((exists(\"+bomb\")\ &&\ &bomb)?\",B\":\"\")}%k\|%Y}%)\ %([%l,%v][%p%%]\ %)
"set statusline=%<%f%m\ \[%{&ff}:%{&fenc}:%Y]\ %{getcwd()}\ \ \[%{strftime('%Y/%b/%d\ %a\ %I:%M\ %p')}\]\ %=\ Line:%l\/%L\ Column:%c%V\ %P
set statusline=%<%f%m\ \ %{getcwd()}\ \ \ %=\ Line:%l\/%L\ Column:%c%V\ %P

set backspace=2
syntax on
"syntax off


let g:solarized_termcolors=256
colorscheme	solarized
set tabstop=2
set shiftwidth=2

set showmatch
set incsearch
"set number
"set cursorline
""set cursorcolumn
set ignorecase
set smartcase
set ai
set smartindent
set foldenable

"By folkes
set wc=<TAB>
set wmnu
set wildmode=list:longest,list:full
set ruler
set ru
set splitbelow
set gdefault
set noedcompatible

set hidden
set history=700

"This will remove the Auto-indetation while copy and Paste
"set paste
"Enables :Paste to just do what you want to paste
nnoremap <F2> :set invpaste paste?<CR>
set pastetoggle=<F2>
set showmode



nmap <F3> :NERDTreeToggle<CR>
nmap ,rc :e $MYVIMRC<cr>
nmap <space> :

autocmd bufwritepost .vimrc source $MYVIMRC 


"Trial from Jackinsella's site See what happens
nnoremap / /\v
vnoremap / /\v
